name: calendario_laboral
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  table_calendar: ^3.2.0
  google_fonts: ^6.3.2
  simple_gesture_detector: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "logo.png"
